apiVersion: v2
name: crowd
description: A chart for installing Crowd DC on Kubernetes
type: application
version: 0.1.0
appVersion:
kubeVersion: ">=1.17.x-0"
keywords:
  - Crowd
  - Crowd Server
  - Crowd Data Center
  - Atlassian
home: https://github.com/atlassian-labs/data-center-helm-charts
sources:
  - https://github.com/atlassian-labs/data-center-helm-charts
deprecated: false
